language: go

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y

go:
  - 1.6

before_script:
  - make setup
  - make deps

script:
  - make build

notifications:
  email: false
