[[constraint]]
  branch = "master"
  name = "github.com/Tomohiro/go-gyazo"

[[constraint]]
  branch = "master"
  name = "github.com/codegangsta/cli"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/skratchdot/open-golang"
